import type { Link, Collection } from './types';

export const mockCollections: Collection[] = [
  { id: '1', name: 'Work', description: 'Links related to work projects', linkCount: 2 },
  { id: '2', name: 'Design Inspiration', description: 'UI/UX design resources', linkCount: 3 },
  { id: '3', name: 'Frontend Frameworks', description: 'Articles and docs about frontend tech', linkCount: 2 },
  { id: '4', name: 'Recipes', description: 'Cooking recipes', linkCount: 1 },
];

export const mockLinks: Link[] = [
  {
    id: '1',
    title: 'Next.js Documentation',
    url: 'https://nextjs.org/docs',
    description: 'The official documentation for Next.js.',
    tags: ['react', 'framework', 'documentation'],
    collectionId: '3',
    isFavorite: true,
    createdAt: '2023-10-26T10:00:00Z',
    updatedAt: '2023-10-26T10:00:00Z',
  },
  {
    id: '2',
    title: 'Figma: The Collaborative Interface Design Tool',
    url: 'https://www.figma.com/',
    description: 'A web-based design tool for creating user interfaces, prototypes, and more.',
    tags: ['design', 'ui', 'ux', 'tool'],
    collectionId: '2',
    isFavorite: false,
    createdAt: '2023-10-25T14:30:00Z',
    updatedAt: '2023-10-25T14:30:00Z',
  },
  {
    id: '3',
    title: 'Project Phoenix - Q4 Roadmap',
    url: 'https://www.notion.so/project-phoenix-q4-roadmap',
    description: 'The roadmap for Project Phoenix for the fourth quarter.',
    tags: ['work', 'project', 'planning'],
    collectionId: '1',
    isFavorite: true,
    createdAt: '2023-10-24T09:00:00Z',
    updatedAt: '2023-10-24T09:00:00Z',
  },
  {
    id: '4',
    title: 'Awwwards - Website Awards',
    url: 'https://www.awwwards.com/',
    description: 'A gallery of the best web design and development from around the world.',
    tags: ['design', 'inspiration', 'web'],
    collectionId: '2',
    isFavorite: false,
    createdAt: '2023-10-23T18:00:00Z',
    updatedAt: '2023-10-23T18:00:00Z',
  },
  {
    id: '5',
    title: 'React Official Website',
    url: 'https://react.dev/',
    description: 'The official website for the React JavaScript library.',
    tags: ['react', 'library', 'documentation'],
    collectionId: '3',
    isFavorite: false,
    createdAt: '2023-10-22T11:45:00Z',
    updatedAt: '2023-10-22T11:45:00Z',
  },
  {
    id: '6',
    title: 'Dribbble - Discover the World’s Top Designers & Creative Professionals',
    url: 'https://dribbble.com/',
    description: 'A community of designers sharing screenshots of their work, process, and projects.',
    tags: ['design', 'ui', 'inspiration'],
    collectionId: '2',
    isFavorite: true,
    createdAt: '2023-10-21T16:20:00Z',
    updatedAt: '2023-10-21T16:20:00Z',
  },
  {
    id: '7',
    title: 'Jira Software | Issue & Project Tracking',
    url: 'https://www.atlassian.com/software/jira',
    description: 'Project management software for agile teams.',
    tags: ['work', 'project-management', 'tool'],
    collectionId: '1',
    isFavorite: false,
    createdAt: '2023-10-20T10:10:00Z',
    updatedAt: '2023-10-20T10:10:00Z',
  },
    {
    id: '8',
    title: 'Best Lasagna Recipe',
    url: 'https://www.allrecipes.com/recipe/23600/worlds-best-lasagna/',
    description: 'A detailed recipe for making delicious homemade lasagna.',
    tags: ['cooking', 'pasta', 'italian'],
    collectionId: '4',
    isFavorite: false,
    createdAt: '2023-10-19T19:00:00Z',
    updatedAt: '2023-10-19T19:00:00Z',
  },
];
